package com.ks.logic.service;

import com.ks.logic.dao.AchieveDAO;
import com.ks.logic.dao.ActivityGiftRecordDAO;
import com.ks.logic.dao.AfficheDAO;
import com.ks.logic.dao.AllianceApplyDAO;
import com.ks.logic.dao.AllianceDAO;
import com.ks.logic.dao.AllianceMembersDAO;
import com.ks.logic.dao.ArenaDAO;
import com.ks.logic.dao.AthleticsInfoDAO;
import com.ks.logic.dao.ChapterChestRecordDAO;
import com.ks.logic.dao.ChatDAO;
import com.ks.logic.dao.ClimbTowerAwardRecordDAO;
import com.ks.logic.dao.ClimbTowerRankDAO;
import com.ks.logic.dao.ClimbTowerUserDAO;
import com.ks.logic.dao.DoubtCheckLogDAO;
import com.ks.logic.dao.FightCheckDAO;
import com.ks.logic.dao.FightPropDAO;
import com.ks.logic.dao.FriendDAO;
import com.ks.logic.dao.FriendGiftDAO;
import com.ks.logic.dao.GameLoggerDAO;
import com.ks.logic.dao.MailDAO;
import com.ks.logic.dao.MailLogDAO;
import com.ks.logic.dao.MonsterDAO;
import com.ks.logic.dao.MysteryItemRecordDAO;
import com.ks.logic.dao.NoticeDAO;
import com.ks.logic.dao.ProductRecordDAO;
import com.ks.logic.dao.SoulExplorationDAO;
import com.ks.logic.dao.SqlDAO;
import com.ks.logic.dao.StatDAO;
import com.ks.logic.dao.SwapArenaDAO;
import com.ks.logic.dao.SwapArenaLogDAO;
import com.ks.logic.dao.UserAllianceDAO;
import com.ks.logic.dao.UserBakPropDAO;
import com.ks.logic.dao.UserBossDAO;
import com.ks.logic.dao.UserBudingDAO;
import com.ks.logic.dao.UserBuffDAO;
import com.ks.logic.dao.UserChapterDAO;
import com.ks.logic.dao.UserDAO;
import com.ks.logic.dao.UserGoodsDAO;
import com.ks.logic.dao.UserMissionDAO;
import com.ks.logic.dao.UserSoulDAO;
import com.ks.logic.dao.UserSoulMapDAO;
import com.ks.logic.dao.UserStatDAO;
import com.ks.logic.dao.UserTeamDAO;
import com.ks.logic.dao.WorldBossDAO;
import com.ks.logic.dao.cfg.AchieveCfgDAO;
import com.ks.logic.dao.cfg.ActivityCfgDAO;
import com.ks.logic.dao.cfg.ActivityGiftCfgDAO;
import com.ks.logic.dao.cfg.AllianceSettingDAO;
import com.ks.logic.dao.cfg.AllianceShopItemDAO;
import com.ks.logic.dao.cfg.AthleticsInfoCfgDAO;
import com.ks.logic.dao.cfg.AwardDAO;
import com.ks.logic.dao.cfg.BossSettingDAO;
import com.ks.logic.dao.cfg.BudingDAO;
import com.ks.logic.dao.cfg.CallRuleDAO;
import com.ks.logic.dao.cfg.CallRuleSoulDAO;
import com.ks.logic.dao.cfg.ChapterAwardDAO;
import com.ks.logic.dao.cfg.ChapterCfgDAO;
import com.ks.logic.dao.cfg.ChapterChestDAO;
import com.ks.logic.dao.cfg.CheckConfigDAO;
import com.ks.logic.dao.cfg.ClimbTowerDAO;
import com.ks.logic.dao.cfg.ClimbTowerStarDAO;
import com.ks.logic.dao.cfg.CoinHandDAO;
import com.ks.logic.dao.cfg.CoinHandRuleDAO;
import com.ks.logic.dao.cfg.EquipmentDAO;
import com.ks.logic.dao.cfg.FriendGiftCfgDAO;
import com.ks.logic.dao.cfg.MallDAO;
import com.ks.logic.dao.cfg.MysteryShopItemDAO;
import com.ks.logic.dao.cfg.ProductDAO;
import com.ks.logic.dao.cfg.ProductItemDAO;
import com.ks.logic.dao.cfg.PropDAO;
import com.ks.logic.dao.cfg.SkillDAO;
import com.ks.logic.dao.cfg.SoulCfgDAO;
import com.ks.logic.dao.cfg.SoulExplorationCfgDAO;
import com.ks.logic.dao.cfg.StaminaDAO;
import com.ks.logic.dao.cfg.StuffDAO;
import com.ks.logic.dao.cfg.SwapArenaSettingDAO;
import com.ks.logic.dao.cfg.TotemRuleDAO;
import com.ks.logic.dao.cfg.TotemSoulDAO;
import com.ks.logic.dao.cfg.UserCfgDAO;
import com.ks.logic.dao.cfg.UserMissionCfgDAO;
import com.ks.logic.dao.dynamic.ActivityDAO;
import com.ks.logic.dao.dynamic.ChapterDAO;
import com.ks.logic.service.impl.ActivityServiceImpl;
import com.ks.logic.service.impl.AfficheServiceImpl;
import com.ks.logic.service.impl.ArenaServiceImpl;
import com.ks.logic.service.impl.AthleticsInfoServiceImpl;
import com.ks.logic.service.impl.AwardServiceImpl;
import com.ks.logic.service.impl.BossServiceImpl;
import com.ks.logic.service.impl.ChapterServiceImpl;
import com.ks.logic.service.impl.CheckFightServiceImpl;
import com.ks.logic.service.impl.ClimbTowerAwardRecordServiceImpl;
import com.ks.logic.service.impl.ClimbTowerRankServiceImpl;
import com.ks.logic.service.impl.ClimbTowerServiceImpl;
import com.ks.logic.service.impl.ClimbTowerStarServiceImpl;
import com.ks.logic.service.impl.ClimbTowerUserServiceImpl;
import com.ks.logic.service.impl.GoodsServiceImpl;
import com.ks.logic.service.impl.MailServiceImpl;
import com.ks.logic.service.impl.MallServiceImpl;
import com.ks.logic.service.impl.MarqueeServiceImpl;
import com.ks.logic.service.impl.ProductItemServiceImpl;
import com.ks.logic.service.impl.ProductServiceImpl;
import com.ks.logic.service.impl.SoulExploretionServiceImpl;
import com.ks.logic.service.impl.SwapArenaServiceImpl;
import com.ks.logic.service.impl.UserAchieveServiceImpl;
import com.ks.logic.service.impl.UserBuffServiceImpl;
import com.ks.logic.service.impl.UserChapterServiceImpl;
import com.ks.logic.service.impl.UserGoodsServiceImpl;
import com.ks.logic.service.impl.UserMissionServiceImpl;
import com.ks.logic.service.impl.UserServiceImpl;
import com.ks.logic.service.impl.UserSoulServiceImpl;
import com.ks.logic.service.impl.UserTeamServiceImpl;
/**
 * 
 * @author ks
 *
 */
public abstract class BaseService {
	//dao
	protected static final UserDAO userDAO = new UserDAO();
	protected static final UserCfgDAO userCfgDAO = new UserCfgDAO();
	protected static final UserSoulDAO userSoulDAO = new UserSoulDAO();
//	protected static final SoulDAO soulDAO = new SoulDAO();
	protected static final SoulCfgDAO soulCfgDAO = new SoulCfgDAO();
	protected static final GameLoggerDAO gameLoggerDAO = new GameLoggerDAO();
	protected static final UserTeamDAO userTeamDAO = new UserTeamDAO();
	protected static final ChapterDAO chapterDAO = new ChapterDAO();
	protected static final ChapterCfgDAO chapterCfgDAO = new ChapterCfgDAO();
	protected static final UserChapterDAO userChapterDAO = new UserChapterDAO();
	protected static final PropDAO propDAO = new PropDAO();
	protected static final EquipmentDAO equipmentDAO = new EquipmentDAO();
	protected static final StuffDAO stuffDAO = new StuffDAO();
	protected static final UserGoodsDAO userGoodsDAO = new UserGoodsDAO();
	protected static final FightPropDAO fightPropDAO = new FightPropDAO();
	protected static final FriendDAO friendDAO = new FriendDAO();
	protected static final UserStatDAO userStatDAO = new UserStatDAO();
	protected static final BudingDAO budingDAO = new BudingDAO();
	protected static final UserBudingDAO userBudingDAO = new UserBudingDAO();
	protected static final ArenaDAO arenaDAO = new ArenaDAO();
	protected static final AfficheDAO afficheDAO = new AfficheDAO();
	protected static final FriendGiftDAO friendGifiDAO = new FriendGiftDAO();
	protected static final FriendGiftCfgDAO friendGifiCfgDAO = new FriendGiftCfgDAO();
	protected static final ActivityDAO activityDAO = new ActivityDAO();
	protected static final ActivityCfgDAO activityCfgDAO = new ActivityCfgDAO();
	protected static final UserSoulMapDAO userSoulMapDAO = new UserSoulMapDAO();
	protected static final AchieveDAO achieveDAO = new  AchieveDAO();
	protected static final AchieveCfgDAO achieveCfgDAO = new AchieveCfgDAO();
	protected static final SkillDAO skillDAO= new  SkillDAO();
	protected static final UserBuffDAO userBuffDAO= new  UserBuffDAO();
	protected static final UserBakPropDAO userBakPropDao= new  UserBakPropDAO();
	protected static final AthleticsInfoDAO athleticsInfoDAO= new  AthleticsInfoDAO();
	protected static final AthleticsInfoCfgDAO athleticsInfoCfgDAO = new AthleticsInfoCfgDAO();
	protected static final SoulExplorationDAO soulExplorationDAO = new SoulExplorationDAO();
	protected static final SoulExplorationCfgDAO soulExplorationCfgDAO = new SoulExplorationCfgDAO();
	protected static final MonsterDAO monsterDAO = new MonsterDAO();
	protected static final UserMissionDAO userMissionDAO= new  UserMissionDAO();
	protected static final UserMissionCfgDAO userMissionCfgDAO= new  UserMissionCfgDAO();
	protected static final MallDAO mallDAO = new MallDAO();
	protected static final SqlDAO sqlDAO = new SqlDAO();
	protected static final ActivityGiftCfgDAO activityGiftDAO = new ActivityGiftCfgDAO();
	protected static final ActivityGiftRecordDAO activityGiftRecordDAO = new ActivityGiftRecordDAO();
	protected static final ProductDAO productDAO = new ProductDAO();
	protected static final ProductItemDAO productItemDAO = new ProductItemDAO();
	protected static final ProductRecordDAO productRecordDAO = new ProductRecordDAO();
	protected static final TotemRuleDAO totemRuleDAO = new TotemRuleDAO();
	protected static final TotemSoulDAO totemSoulDAO = new TotemSoulDAO();
	protected static final CallRuleDAO callRuleDAO = new CallRuleDAO();
	protected static final CallRuleSoulDAO callRuleSoulDAO = new CallRuleSoulDAO();
	protected static final CoinHandDAO coinHandDAO = new CoinHandDAO();
	protected static final CoinHandRuleDAO coinHandRuleDAO = new CoinHandRuleDAO();
	protected static final StaminaDAO staminaDAO = new StaminaDAO();
	protected static final BossSettingDAO bossSettingDAO = new BossSettingDAO();
	protected static final WorldBossDAO worldBossDAO = new WorldBossDAO();
	protected static final UserBossDAO userBossDAO = new UserBossDAO();
	protected static final ClimbTowerDAO climbTowerDAO = new ClimbTowerDAO();
	protected static final AwardDAO climbTowerAwardDAO = new AwardDAO();
	protected static final ClimbTowerStarDAO climbTowerStarDAO = new ClimbTowerStarDAO();
	protected static final ClimbTowerAwardRecordDAO climbTowerAwardRecordDAO = new ClimbTowerAwardRecordDAO();
	protected static final ClimbTowerRankDAO climbTowerRankDAO = new ClimbTowerRankDAO();
	protected static final ClimbTowerUserDAO climbTowerUserDAO = new ClimbTowerUserDAO();
	protected static final ChapterAwardDAO chapterAwardDAO = new ChapterAwardDAO();
	protected static final ChapterChestDAO chapterChestDAO = new ChapterChestDAO();
	protected static final ChapterChestRecordDAO chapterChestRecordDAO = new ChapterChestRecordDAO();
	protected static final ChatDAO chatDAO = new ChatDAO();
	protected static final StatDAO statDAO = new StatDAO();
	protected static final SwapArenaSettingDAO robotDAO = new SwapArenaSettingDAO();
	protected static final SwapArenaDAO swapArenaDAO = new SwapArenaDAO();
	protected static final SwapArenaLogDAO swapArenaLogDAO = new SwapArenaLogDAO();
	protected static final MysteryShopItemDAO mysteryShopItemDAO = new MysteryShopItemDAO();
	protected static final MysteryItemRecordDAO mysteryItemRecordDAO = new MysteryItemRecordDAO();
	protected static final FightCheckDAO fightCheckDAO = new FightCheckDAO();
	protected static final DoubtCheckLogDAO doubtCheckLogDAO = new DoubtCheckLogDAO();
	protected static final CheckConfigDAO checkConfigDAO = new CheckConfigDAO();
	protected static final AllianceDAO allianceDAO = new AllianceDAO();
	protected static final AllianceMembersDAO allianceMembersDAO = new AllianceMembersDAO();
	protected static final UserAllianceDAO userAllianceDAO = new UserAllianceDAO();
	protected static final AllianceApplyDAO allianceApplyDAO = new AllianceApplyDAO();
	protected static final AllianceSettingDAO allianceSettingDAO = new AllianceSettingDAO();
	protected static final AllianceShopItemDAO allianceShopItemDAO = new AllianceShopItemDAO();
	protected static final NoticeDAO noticeDAO = new NoticeDAO();
	protected static final MailDAO mailDAO = new MailDAO();
	protected static final MailLogDAO mailLogDAO = new MailLogDAO();
	
	//service
	protected static final UserService userService = new UserServiceImpl();
	protected static final UserSoulService userSoulService = new UserSoulServiceImpl();
	protected static final UserTeamService userTeamService = new UserTeamServiceImpl();
	protected static final UserGoodsService userGoodsService = new UserGoodsServiceImpl();
	protected static final ArenaService arenaService = new ArenaServiceImpl();
	protected static final ActivityService activityService = new ActivityServiceImpl();
	protected static final AfficheService  afficheService= new AfficheServiceImpl();
	protected static final UserAchieveService  userAchieveService= new UserAchieveServiceImpl();
	protected static final UserBuffService  userBuffService= new UserBuffServiceImpl();
	protected static final AthleticsInfoService athleticsInfoService= new  AthleticsInfoServiceImpl();
	protected static final SoulExploretionService soulExploretionService= new  SoulExploretionServiceImpl();
	protected static final ChapterService chapterService=new ChapterServiceImpl();
	protected static final UserMissionService userMissionService = new UserMissionServiceImpl();
	protected static final MallService mallService = new MallServiceImpl();
	protected static final ProductService productService = new ProductServiceImpl();
	protected static final ProductItemService productItemService = new ProductItemServiceImpl();
	protected static final GoodsService goodsService = new GoodsServiceImpl();
	protected static final BossService bossService = new BossServiceImpl();
	protected static final UserChapterService userChapterService = new UserChapterServiceImpl();
	protected static final ClimbTowerService climbTowerService = new ClimbTowerServiceImpl();
	protected static final AwardService climbTowerAwardService = new AwardServiceImpl();
	protected static final ClimbTowerStarService climbTowerStarService = new ClimbTowerStarServiceImpl();
	protected static final ClimbTowerAwardRecordService climbTowerAwardRecordService = new ClimbTowerAwardRecordServiceImpl();
	protected static final ClimbTowerRankService climbTowerRankService = new ClimbTowerRankServiceImpl();
	protected static final ClimbTowerUserService climbTowerUserService = new ClimbTowerUserServiceImpl();
	protected static final SwapArenaService swapArenaService = new SwapArenaServiceImpl();
	protected static final CheckFightService checkFightService = new CheckFightServiceImpl();
	protected static final MarqueeService marqueeService = new MarqueeServiceImpl();
	protected static final MailService mailService = new MailServiceImpl();
	
}
